/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package injector

import injector.View.EventApp
import tornadofx.launch


fun main(args: Array<String>) {
    launch<EventApp>(args)
}
