/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package injector

import injector.View.EventApp
import io.grpc.injector.InjectorGrpc
import tornadofx.launch


fun main(args: Array<String>) {
//    val dc = DataAccessor("127.0.0.1:4222", "SNR")
//    dc.fetchModuleInfo().mapLeft { println("${it.msg}") }.map { println(it.paramPaths) }
    launch<EventApp>(args)

}
