/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package injector

import javafx.application.Application
import javafx.scene.text.FontWeight
import mu.KotlinLogging
import tornadofx.*

fun main(args: Array<String>) {
    val logger = KotlinLogging.logger {}

    logger.debug { "helloo" }
//    Application.launch(HelloWorldApp::class.java, *args)
}

class HelloWorldApp : App(HelloWorld::class, Styles::class) {

}

class Styles : Stylesheet() {
    init {
        label {
            fontSize = 20.px
            fontWeight = FontWeight.BOLD
            backgroundColor += c("#cecece")
        }
    }
}

class HelloWorld : View() {
    override val root = hbox {
        label("Hello world")
    }


}